#!/usr/bin/env bash
# Regenerates port/shard_rename.h from the symbols actually exported by a
# compiled liblwip.a. Run after changing the exported C surface (new files,
# new lwip_rs_* accessors), then commit the header.
#
#   cargo build && scripts/gen-shard-rename.sh
set -euo pipefail
cd "$(dirname "$0")/.."

ARCHIVE=$(ls -t target/debug/build/lwip-*/out/liblwip.a 2>/dev/null | head -1)
[[ -n "$ARCHIVE" ]] || { echo "no liblwip.a under target/; run cargo build first" >&2; exit 1; }

OUT=port/shard_rename.h
{
    cat <<'HDR'
/* Generated by scripts/gen-shard-rename.h — do not edit by hand.
 *
 * When PANDA_LWIP_SHARD_PREFIX is defined, every symbol the lwIP core and
 * its port export is renamed with that prefix via token pasting. Compiling
 * the identical sources once per prefix yields multiple fully independent
 * stack instances (separate globals, pools, pcb lists, timers) linkable
 * into one process. The primary stack compiles WITHOUT the prefix and is
 * byte-for-byte unaffected.
 */
#ifndef PANDA_LWIP_SHARD_RENAME_H
#define PANDA_LWIP_SHARD_RENAME_H
#ifdef PANDA_LWIP_SHARD_PREFIX

#define PANDA_LWIP_PASTE2(a, b) a##b
#define PANDA_LWIP_PASTE(a, b) PANDA_LWIP_PASTE2(a, b)
#define PANDA_LWIP_RENAME(sym) PANDA_LWIP_PASTE(PANDA_LWIP_SHARD_PREFIX, sym)

/* def.c's byte-swap and string helpers are stateless, so shards share the
 * primary stack's copy instead of renaming. def.h/def.c wrap each in an
 * overridability guard (#ifndef lwip_htons etc.); the self-referential
 * defines trip those guards so shard TUs neither redeclare nor redefine the
 * symbols (a shard-side definition would collide with the primary's at link
 * time), while call sites still expand to plain calls. The prototypes the
 * guards suppressed are restored below; stdint.h/stddef.h are freestanding
 * and safe this early. */
#define lwip_htons lwip_htons
#define lwip_htonl lwip_htonl
#define lwip_itoa lwip_itoa
#define lwip_strnicmp lwip_strnicmp
#define lwip_stricmp lwip_stricmp
#define lwip_strnstr lwip_strnstr
#define lwip_strnistr lwip_strnistr
#define lwip_memcmp_consttime lwip_memcmp_consttime
#include <stdint.h>
#include <stddef.h>
uint16_t lwip_htons(uint16_t n);
uint32_t lwip_htonl(uint32_t n);
void lwip_itoa(char *result, size_t bufsize, int number);
int lwip_strnicmp(const char *str1, const char *str2, size_t len);
int lwip_stricmp(const char *str1, const char *str2);
char *lwip_strnstr(const char *buffer, const char *token, size_t n);
char *lwip_strnistr(const char *buffer, const char *token, size_t n);
int lwip_memcmp_consttime(const void *s1, const void *s2, size_t len);

HDR
    {
        nm -g --defined-only "$ARCHIVE" 2>/dev/null \
            | awk '$2 ~ /^[TDBSC]$/ {print $3}' \
            | sed 's/^_//'
        # port/sys_arch.c's _WIN32 block exports these, so they never show up
        # when nm reads a mac/linux archive. critSec and the protect pair are
        # per-stack state — sharing them would serialize shards against each
        # other — so they must rename like everything else.
        printf '%s\n' \
            critSec \
            lwip_win32_platform_diag \
            sys_arch_protect \
            sys_arch_unprotect \
            sys_init \
            sys_jiffies \
            sys_win_rand
        # mem.c's static heap (LWIP_DECLARE_MEMORY_ALIGNED) only exists when
        # MEM_LIBC_MALLOC=0 — the Android profile. Desktop scan archives use
        # libc malloc and never export it, so list it explicitly; each shard
        # must own its heap or their allocators would collide at link time.
        printf '%s\n' \
            ram_heap
    } \
        | sort -u \
        | grep -v -x \
            -e lwip_htons -e lwip_htonl \
            -e lwip_itoa -e lwip_strnicmp -e lwip_stricmp \
            -e lwip_strnstr -e lwip_strnistr -e lwip_memcmp_consttime \
        | awk '{printf "#define %s PANDA_LWIP_RENAME(%s)\n", $1, $1}'
    cat <<'FTR'

#endif /* PANDA_LWIP_SHARD_PREFIX */
#endif /* PANDA_LWIP_SHARD_RENAME_H */
FTR
} > "$OUT"
echo "wrote $OUT ($(grep -c PANDA_LWIP_RENAME\( "$OUT") renames)"
